name: Clang Format Check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install clang-format
        run: pip install clang-format

      - name: Check code format
        run: |
          FILES=$(git ls-files 'cpp/*.cpp' 'cpp/*.h')
          clang-format -i $FILES
          git diff --exit-code
