name: Build and Test

on:
  push:
    branches:
      - "**"
  pull_request:
    paths:
      - "cpp/**"

jobs:
  build_and_test:
    name: Build  and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "5.15.2"
          target: "desktop"
      - name: Build and test
        run: cd cpp && cmake . && cmake --build . --verbose && ctest . --verbose
